#! /usr/bin/ksh .
tableName=$1
targetTable=$DBPATH'/'$tableName'.tbl'

if ! test -f $targetTable
then
echo "Not existed Table...!"
exit 1
fi
typeset -fx function anliesRef
{
ref=`line<$targetTable`
hd="#include<"
typeset -i rlen
rlen=${#ref}
typeset -i x
((x=$rlen-10))
str1=`echo ${ref:${#hd}:x}`
str2=`echo $str1 | tr "@" "\n"`
typeset -i ii
for mm in $str2
do
arr[ii]=$mm
((ii++))
done
}

if test $# -gt 0
then
tname=`echo ${arr[1]}|tr ":" " "`
echo "* Warning: you will delete <"$tname">"
echo "Do you want to continue?"
select ans in "Yes" "No"
do
case $REPLY in
1)

sed  "/${tname}/,/${tname}/d" ${arr[0]} > $LOGFILE"tmp"
cat $LOGFILE"tmp" >$LOGFILE
rm $LOGFILE"tmp"
rm $DBPATH"/"$tableName".tbl"
echo "* Table "$tableName " was been deleted.."
;;
2)
;;
esac
done

fi

